### ISSUE TITLE
tutorial missing

### ISSUE THREAD

**Issue by laszewsk** [cloudmesh-community/hid-sp18-523#10]
the submitted link

URL tutorial: https://github.com/cloudmesh-community/hid-sp18-523/blob/master/tutorial/puppet.md

is not working

**Comment by tandon-ritz** [comment]
Hi Professor,

Earlier there was github issue raised to delete the tutorial folder as it was duplicate; so I deleted it. I did my tutorial along with hid-sp18-520; tutorial folder under 520 is the latest one.

Thanks,
Ritesh

**Comment by laszewsk** [comment]
I am confused

where is the code where is the document? We must have only one ...

**Comment by laszewsk** [comment]
why would you not do the tutorial about your code not in the folder where you have your code?
It is unclear to me what is happening, please communicate in a message to me who is doing wheat where.

**Comment by laszewsk** [comment]
Also the subbmitted link https://github.com/cloudmesh-community/hid-sp18-523/blob/master/tutorial/puppet.md

does not work what is the tutorial and why does puppet have something to do with your project?

**Comment by laszewsk** [comment]
I think you have two issues

a) a tutorial such as the one from puppet about a technology
b) a tutorial to showcase how to use your code.

**Comment by tandon-ritz** [comment]
Thanks for your valuable feedback professor 
Path of puppet tutorial is added in readme.
Steps to showcase how to reproduce and execute code locally has been added in project report md file.

Thanks helping us improve our documentation and code quality.
