### ISSUE TITLE
yaml file

### ISSUE THREAD

**Issue by laszewsk** [cloudmesh-community/hid-sp18-523#12]
Hmm looking at this 

https://github.com/cloudmesh-community/hid-sp18-523/blob/master/project-code/prediction.yaml

this is pretty sparse. Where is data, where is documentation of this? I can not even find that documented in the report.

**Comment by tandon-ritz** [comment]
Thanks for providing valuable feedback and suggestion and helping us improve our project report. I have added link of test and train dataset used in our project in the report md.
